### ISSUE TITLE
postgres_exporter fail after postgres update to 32 version(11.1)

### ISSUE THREAD

**Issue by Alexvianet** [bosh-prometheus/prometheus-boshrelease#265]
for some resone postgres_exporter failed 
```
goroutine 4 [running]:
main.(*pgSetting).metric(0xc4201f45f0, 0xc4201c1da0, 0x5)
        /home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/pg_setting.go:69 +0x52b
main.querySettings(0xc4201b8000, 0xc42017d040, 0x0, 0x0)
        /home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/pg_setting.go:38 +0x215
main.(*Exporter).scrape(0xc4201ae100, 0xc4201b8000)
        /home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:1048 +0x4a8
main.(*Exporter).Collect(0xc4201ae100, 0xc4201b8000)
        /home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:767 +0x3c
main.(*Exporter).Describe(0xc4201ae100, 0xc420064540)
        /home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:760 +0xb0
github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Register.func1(0x92a4e0, 0xc4201ae100, 0xc420064540)
        /home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:242 +0x3b
created by github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Register
        /home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:241 +0x14e
time="2018-11-24T15:32:58Z" level=info msg="Established new database connection." source="postgres_exporter.go:995"
time="2018-11-24T15:32:58Z" level=info msg="Semantic Version Changed: 0.0.0 -> 11.1.0" source="postgres_exporter.go:925"
panic: Unknown unit for runtime variable: "B"
```

I think postgres_exporter need to be updated to work with latest https://github.com/cloudfoundry/postgres-release

https://github.com/wrouesnel/postgres_exporter/releases latest release can help:
![screenshot from 2018-11-24 17-39-18](https://user-images.githubusercontent.com/17483589/48970038-eca1c300-f00f-11e8-8b32-f72e9ba1d814.png)

**Comment by frodenas** [comment]
Fixed at https://github.com/bosh-prometheus/prometheus-boshrelease/commit/b4e08b63469e302b48b7170bbcb35f463c4b96bb.
